//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ei.Agents.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ei.Agents.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; performed action &apos;{1}&apos; with parameters: &apos;{2}&apos;.
        /// </summary>
        public static string ActionPerformed {
            get {
                return ResourceManager.GetString("ActionPerformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; moved to &apos;{1}&apos; in workflow &apos;{2}&apos; [{3}].
        /// </summary>
        public static string ChangedState {
            get {
                return ResourceManager.GetString("ChangedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; entered institution &apos;{2}&apos; - {1}.
        /// </summary>
        public static string EnteredInstitution {
            get {
                return ResourceManager.GetString("EnteredInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; entered workflow &apos;{2} [{1}]&apos;.
        /// </summary>
        public static string EnteredWorkflow {
            get {
                return ResourceManager.GetString("EnteredWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; exited institution.
        /// </summary>
        public static string ExitedInstitution {
            get {
                return ResourceManager.GetString("ExitedInstitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; exited workflow &apos;{2} [{1}]&apos; to &apos;{4} [{3}]&apos;.
        /// </summary>
        public static string ExitedWorkflow {
            get {
                return ResourceManager.GetString("ExitedWorkflow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution &apos;{0}&apos; started  .
        /// </summary>
        public static string InstitutionStarted {
            get {
                return ResourceManager.GetString("InstitutionStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to werwerwer.
        /// </summary>
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State &apos;{2}&apos; timed out at workflow &apos;{0} [{1}]&apos; .
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agent &apos;{0}&apos; is waiting for decision.
        /// </summary>
        public static string WaitingForDecision {
            get {
                return ResourceManager.GetString("WaitingForDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow &apos;{1} [{2}]&apos; changed state to &apos;{0}&apos;.
        /// </summary>
        public static string WorkflowChangedState {
            get {
                return ResourceManager.GetString("WorkflowChangedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting parameter &apos;{2} = {3}&apos; in workflow {0} [{1}] .
        /// </summary>
        public static string WorkflowParameterChanged {
            get {
                return ResourceManager.GetString("WorkflowParameterChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workflow &apos;{0} [{1}]&apos; started.
        /// </summary>
        public static string WorkflowStarted {
            get {
                return ResourceManager.GetString("WorkflowStarted", resourceCulture);
            }
        }
    }
}
