//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ei.Core.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Ei.Core.Ei.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ActionPerformed {
            get {
                return ResourceManager.GetString("ActionPerformed", resourceCulture);
            }
        }
        
        public static string ChangedState {
            get {
                return ResourceManager.GetString("ChangedState", resourceCulture);
            }
        }
        
        public static string EnteredInstitution {
            get {
                return ResourceManager.GetString("EnteredInstitution", resourceCulture);
            }
        }
        
        public static string EnteredWorkflow {
            get {
                return ResourceManager.GetString("EnteredWorkflow", resourceCulture);
            }
        }
        
        public static string ExitedInstitution {
            get {
                return ResourceManager.GetString("ExitedInstitution", resourceCulture);
            }
        }
        
        public static string ExitedWorkflow {
            get {
                return ResourceManager.GetString("ExitedWorkflow", resourceCulture);
            }
        }
        
        public static string InstitutionStarted {
            get {
                return ResourceManager.GetString("InstitutionStarted", resourceCulture);
            }
        }
        
        public static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        public static string WaitingForDecision {
            get {
                return ResourceManager.GetString("WaitingForDecision", resourceCulture);
            }
        }
        
        public static string WorkflowChangedState {
            get {
                return ResourceManager.GetString("WorkflowChangedState", resourceCulture);
            }
        }
        
        public static string WorkflowParameterChanged {
            get {
                return ResourceManager.GetString("WorkflowParameterChanged", resourceCulture);
            }
        }
        
        public static string WorkflowStarted {
            get {
                return ResourceManager.GetString("WorkflowStarted", resourceCulture);
            }
        }
    }
}
